### ISSUE TITLE
Mobile: closing a deposite add iusd instead of sending them back

### ISSUE THREAD

**Issue by pascalSAINVITU** [byteball/bonded-stablecoin-ui#27]
I click here:
![Screenshot_20201025_221511](https://user-images.githubusercontent.com/22096367/97119580-8a78fd80-1711-11eb-83eb-c79affa4c82e.jpg) and the wallet opens here:
![Screenshot_20201025_221539_org byteball wallet](https://user-images.githubusercontent.com/22096367/97119591-9795ec80-1711-11eb-9db0-3b7a8b604c8c.jpg)

**Comment by tarmo888** [comment]
Fixed in #28
