### ISSUE TITLE
Live token info not visible on mobile

### ISSUE THREAD

**Issue by pmiklos** [byteball/bonded-stablecoin-ui#7]
On desktop there's a nice live view of the current state of the token supply and target price etc. That is a very useful panel and unfortunately it is not visible on mobile screens. At least it's not visible in my Android, Pixel 3 device.
It might be intentional to save space for the trading and deposit, governance tabs, but it would still be nice to have it somehow maybe as a collapsible panel of some sort?

**Comment by tonyofbyteball** [comment]
This was fixed in a recent update.
